### ISSUE TITLE
ZeroDivisionError when trying to print the findings 

### ISSUE THREAD

**Issue by bjakw** [kazet/wpgarlic#2]
Hello there, thank you for your research, I have a question regarding the tool. At first after installing, I had to tweak the dependencies versions a little bit to get it to work, and it worked perfectly afterward and I was able to fuzz and see the findings of the fuzzing.
But as soon as I started to fuzz the next plugin, the findings printer stopped working properly and it started to raise an Exception for Zero Division Error:

>┌──(venv)─(root@kali)-[~/wpgarlic]
└─# bin/print_findings data/plugin_fuzz_results/  
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]data/plugin_fuzz_results/pdf-generator-for-wp_4b256ea0c30ed8675326896c750f21be.json
Nothing found in pdf-generator-for-wp_4b256ea0c30ed8675326896c750f21be.json. Archiving the report...
data/plugin_fuzz_results/scanned/pdf-generator-for-wp_4b256ea0c30ed8675326896c750f21be.json:     84.3% -- replaced with data/plugin_fuzz_results/scanned/pdf-generator-for-wp_4b256ea0c30ed8675326896c750f21be.json.gz
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:34<00:00, 34.74s/it]
Unique filepaths total: 1
Filepaths with report printed: 0 (0.00%)
                                                                                                                       
>┌──(venv)─(root@kali)-[~/wpgarlic]
└─# bin/print_findings data/plugin_fuzz_results/
0it [00:00, ?it/s]
Unique filepaths total: 0
Traceback (most recent call last):
  File "/root/wpgarlic/print_findings.py", line 250, in <module>
    typer.run(print_findings_from_folder)
  File "/root/wpgarlic/venv/lib/python3.9/site-packages/typer/main.py", line 864, in run
    app()
  File "/root/wpgarlic/venv/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/root/wpgarlic/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/wpgarlic/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/wpgarlic/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/wpgarlic/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/wpgarlic/venv/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/root/wpgarlic/print_findings.py", line 245, in print_findings_from_folder
    f"({100.0 * num_paths_with_printed_reports / len(file_names):.02f}%)"
ZeroDivisionError: float division by zero

I deleted all containers and images and deleted the project folder and rebuilt the whole thing from scratch but that sadly didn't help.
I can see that the Fuzzing is happening in the first stage and the huge findings .Json file being created, but then the reporter prints that it couldn't find anything even though I'm testing the same plugin I tested before and I'm sure that there are some findings at least.
Do you have an Idea what might be causing this and how to fix it ? 
Thanks a lot !

**Comment by kazet** [comment]
Hi,

Thanks for the report!

I see multiple issues here ;)

# Dependencies
"I had to tweak the dependencies versions a little bit to get it to work". I can reproduce that with old dependencies versions I've observed the `ImportError: cannot import name 'get_terminal_size' from 'click.termui'` message - I have **bumped the requirements.txt versions to the latest ones**. Would you share what tweaks were needed and whether the one I've added are sufficient?
# ZeroDivisionError
ZeroDivisionError was caused by lack of reports to print. During the first `print_findings` run, the report was seen to not contain anything interesting and therefore **gzipped and archived**. During the second run, there were no reports anymore (as the first one is archived) and that caused the `ZeroDivisionError`. This bug is now **fixed**.
# Not finding a bug
"the reporter prints that it couldn't find anything even though I'm testing the same plugin I tested before and I'm sure that there are some findings at least". What do you mean that there are findings?
1. If you mean that earlier fuzzing for the same plugin and version showed some crashes - that is definitely possible - fuzzer performs multiple decisions based on randomness (e.g. payload choice) so it may be possible that it finds a bug in one run and not other.
2. If instead you mean that you know from looking at the plugin source or from a CVE that there's a vulnerability in this particular plugin version, and fuzzer doesn't find it, you will need to check whether the fuzzer could find it - what type of bug is it? The fuzzer won't catch complex logic bugs. If you want, check what tweaks are needed to the fuzzer to catch this type of bugs - maybe adding a new type of payload?
If you would add such support, it would be **awesome** - but remember to add an end-to-end test similar to the ones existing in the code.

Kind regards,

**Comment by bjakw** [comment]
> Hi,
> 
> Thanks for the report!
> 
> I see multiple issues here ;)
> 
> # Dependencies
> "I had to tweak the dependencies versions a little bit to get it to work". I can reproduce that with old dependencies versions I've observed the `ImportError: cannot import name 'get_terminal_size' from 'click.termui'` message - I have **bumped the requirements.txt versions to the latest ones**. Would you share what tweaks were needed and whether the one I've added are sufficient?
> 
> # ZeroDivisionError
> ZeroDivisionError was caused by lack of reports to print. During the first `print_findings` run, the report was seen to not contain anything interesting and therefore **gzipped and archived**. During the second run, there were no reports anymore (as the first one is archived) and that caused the `ZeroDivisionError`. This bug is now **fixed**.
> 
> # Not finding a bug
> "the reporter prints that it couldn't find anything even though I'm testing the same plugin I tested before and I'm sure that there are some findings at least". What do you mean that there are findings?
> 
> 1. If you mean that earlier fuzzing for the same plugin and version showed some crashes - that is definitely possible - fuzzer performs multiple decisions based on randomness (e.g. payload choice) so it may be possible that it finds a bug in one run and not other.
> 2. If instead you mean that you know from looking at the plugin source or from a CVE that there's a vulnerability in this particular plugin version, and fuzzer doesn't find it, you will need to check whether the fuzzer could find it - what type of bug is it? The fuzzer won't catch complex logic bugs. If you want, check what tweaks are needed to the fuzzer to catch this type of bugs - maybe adding a new type of payload?
>    If you would add such support, it would be **awesome** - but remember to add an end-to-end test similar to the ones existing in the code.
> 
> Kind regards,

Hi, YES this is exactly the error I faced with the old dependencies, I also did the same changes you did to the dependencies and I additionally added a slightly older version for "click" (a dependency for typer) and I installed click 8.0.4 instead of 8.1.2. and it worked.

Thanks for the clarification regarding the ZeroDivisionError and the Fuzzing, I actually meant that I did a first run with a specific version of a plugin and was able to see a couple of crashes with some payloads and then refuzzed the same plugin multiple times after that and I didn't get a single crash!, that's why I was a bit confused and thought that I was doing something wrong. 

I find your approach to WordpressPlugins very promising and I will definitely spend some time with your code to see what other vulnerabilities/payloads could be tested and I will certainly share my changes in case I added some useful functionality.

Thank you again for sharing.
