### ISSUE TITLE
Not Getting the Expected Behavior

### ISSUE THREAD

**Issue by mike268x** [kazet/wpgarlic#3]
Hi,

When executing the following command, I don't get any results:

```
./bin/fuzz_plugin responsive-vector-maps --version 6.4.0
```

```
./bin/print_findings data/plugin_fuzz_results/
  0%|                                                                                             | 0/1 [00:00<?, ?it/s]data/plugin_fuzz_results/responsive-vector-maps_2ebc606988056f9282e287708b380297.json
Nothing found in responsive-vector-maps_2ebc606988056f9282e287708b380297.json. Archiving the report...
data/plugin_fuzz_results/scanned/responsive-vector-maps_2ebc606988056f9282e287708b380297.json:	 11.5% -- replaced with data/plugin_fuzz_results/scanned/responsive-vector-maps_2ebc606988056f9282e287708b380297.json.gz
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 677.05it/s]
Unique filepaths total: 1
Filepaths with report printed: 0 (0.00%)
```

The only change I made is changing the version to "3.3" in docker-compose.yaml
Here are the logs of the installation. Let me know if you spot any issue:

[wpgarlic_install_logs.txt](https://github.com/kazet/wpgarlic/files/9401181/wpgarlic_install_logs.txt)

**Comment by kazet** [comment]
Hello!

I have checked a fresh installation of wpgarlic (master, commit 6df241b084a768a6c1e18bbc021573bff52199dd) and after setting version to 3.3 in docker-compose.yml the fuzzing works and provides expected results (Docker 20.10.12, docker-compose 1.29.2).

Please provide a log from the fuzzing command (`./bin/fuzz_plugin ...`) so that we can debug it further.

Besides, it is possible that a fuzzing run didn't find anything due to chance - there is a lot of randomness in how the fuzzer works (e.g. in the payload choice) - and subsequent fuzzing runs of the same plugin version would find bugs. Is it the case?
